server:
  port: 8084
spring:
  application:
    name: user
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://120.79.216.102:3306/lst?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: sdzn2019
      driver-class-name: com.mysql.jdbc.Driver
      stat-view-servlet:
        login-username: admin
        login-password: admin
